export const TODOS_REQUEST = 'TODOS_REQUEST';
export const TODOS_RESOLVE = 'TODOS_RESOLVE';
export const TODOS_REJECT  = 'TODOS_REJECT';

export const CREATE_TODOS_RESOLVE = 'CREATE_TODOS_RESOLVE';
export const CREATE_TODOS_REJECT  = 'CREATE_TODOS_REJECT';

export const UPDATE_TODOS_RESOLVE = 'UPDATE_TODOS_RESOLVE';
export const UPDATE_TODOS_REJECT  = 'UPDATE_TODOS_REJECT';

export const REMOVE_TODOS_RESOLVE = 'REMOVE_TODOS_RESOLVE';
export const REMOVE_TODOS_REJECT  = 'REMOVE_TODOS_REJECT';